version: '3.4'

services:
  catalogdb:
    image: mongo

  geocodingservice:
    image: ${DOCKER_REGISTRY-}geocodingservice
    build:
      context: .
      dockerfile: GeocodingService/Dockerfile

volumes:
  mongo_data: